version: '3'
services:
  navigation-dev:
    build:
      context: .
    image: navigation-summer
    container_name: navigation-summer2
    stdin_open: true
    tty: true
    privileged: true


    network_mode: host
    working_dir: /home/user/Eurobot2025-Navigation-ws

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - $HOME/.Xauthority:/home/user/.Xauthority
      - D:\Justin\navigation:/home/user/Eurobot2025-Navigation-ws

    environment:
      - DISPLAY=172.31.96.1:0.0
      - XAUTHORITY=/home/user/.Xauthority

    command: /bin/bash