#------------------MAP--------------------

# |-------------------------------------|
# |    |   |    | ------- | 13 |   | 17 |
# |_*1_|   |_*7_|   9     |____|   |____|
# |                                |*19 |
# |   *3     5   *11        15     |    |
# |------                          -----|
# |   *4     8               *16   | 18 |
# |____     ____   *10     ____    |____|
# | *2 |   |    |   12    |    |   |    |
# |    |   | 6  | ------- |  *14   | 20 |    
# |-------------------------------------|

# *means there is an offset to avoid collisions

#----------------POINTS-------------------
#1*
# initial place
# - xyz: [path, 0.35, 1.00, 0]
# # plant D
# - xyz: [path, 0.65, 0.70, 0]
# - xyz: [dock, 0.65, 0.70, 0]
# - xyz: [dock, 0.85, 0.70, 0]
# # - xyz: [dock, 0.65, 0.70, 0]
# - xyz: [dock, 0.65, 0.70, 3.14159]
# - xyz: [dock, 1.00, 0.70, 3.14129]
# # - xyz: [dock, 0.65, 0.70, 0]
# # plant E
# - xyz: [path, 1.15, 0.50, 0]
# - xyz: [dock, 1.15, 0.50, 0]
# - xyz: [dock, 1.35, 0.50, 0]
# - xyz: [dock, 1.15, 0.50, 0]
# - xyz: [dock, 1.15, 0.50, 3.14159]
# - xyz: [dock, 1.50, 0.50, 3.14159]
# - xyz: [dock, 1.15, 0.50, 0]
# # plant F
# - xyz: [path, 1.65, 0.70, 0]
# - xyz: [dock, 1.65, 0.70, 0]
# - xyz: [dock, 1.85, 0.70, 0]
# - xyz: [dock, 1.65, 0.70, 0]
# - xyz: [dock, 1.65, 0.70, 3.14159]
# - xyz: [dock, 2.00, 0.70, 3.14159]
# - xyz: [dock, 1.65, 0.70, 0]
# # get pot
# - xyz: [path, 2.05, 1.40, 0]
# - xyz: [dock, 2.05, 1.40, 0]
# - xyz: [dock, 2.25, 1.40, 0]
# - xyz: [dock, 2.05, 1.40, 0]
# - xyz: [dock, 2.05, 1.40, 3.14159]
# - xyz: [dock, 2.25, 1.40, 3.14159]
# - xyz: [dock, 2.05, 1.40, 0]
# # put plant
# - xyz: [path, 2.05, 1.60, 0]
# - xyz: [dock, 2.05, 1.60, 0]
# - xyz: [dock, 2.25, 1.60, 0]
# - xyz: [dock, 2.05, 1.60, 0]
# - xyz: [dock, 2.05, 1.60, 3.14159]
# - xyz: [dock, 2.25, 1.60, 3.14159]
# - xyz: [dock, 2.05, 1.60, 0]
# # put room 1
# - xyz: [path, 2.05, 1.40, 0]
# - xyz: [dock, 2.05, 1.40, 0]
# - xyz: [dock, 2.25, 1.40, 0]
# - xyz: [dock, 2.05, 1.40, 0]
# - xyz: [dock, 2.05, 1.40, 3.14159]
# - xyz: [dock, 2.25, 1.40, 3.14159]
# - xyz: [dock, 2.05, 1.40, 0]
# # put room 2
# - xyz: [path, 2.05, 1.60, 0]
# - xyz: [dock, 2.05, 1.60, 0]
# - xyz: [dock, 2.25, 1.60, 0]
# - xyz: [dock, 2.05, 1.60, 0]
# - xyz: [dock, 2.05, 1.60, 3.14159]
# - xyz: [dock, 2.25, 1.60, 3.14159]
# - xyz: [dock, 2.05, 1.60, 0]
# # solar mission
# - xyz: [path, 1.90, 0.40, 1.57]
# - xyz: [dock, 1.90, 0.40, 1.57]
# - xyz: [dock, 1.90, 0.20, 0]
# - xyz: [dock, 1.60, 0.20, 0]
# - xyz: [dock, 1.40, 0.20, 0]
# - xyz: [dock, 0.10, 0.20, 0]


# # initial place
# - xyz: [path, 0.35, 1.00, 0]
# - xyz: [path,0.7, 0.7, 0.0]  
# # - xyz: [dock,0.7, 0.7, 0.0]    
# - xyz: [dock,0.86, 0.7, 0.0]   # Planter-A
# - xyz: [dock,0.75, 0.7, 3.14]
# - xyz: [dock,0.93, 0.7, 3.14]
# - xyz: [path,0.7, 1.3, 0.0] 
# # - xyz: [dock,0.7, 1.3, 0.0]    
# - xyz: [dock,0.86, 1.3, 0.0]   # Planter-B
# - xyz: [dock,0.75, 1.3, 3.14]
# - xyz: [dock,0.93, 1.3, 3.14]
# - xyz: [path,1.2, 0.5, 0.0] 
# # - xyz: [dock,1.2, 0.5, 0.0]    
# - xyz: [dock,1.36, 0.5, 0.0]   # Planter-C
# - xyz: [dock,1.25, 0.5, 3.14]
# - xyz: [dock,1.43, 0.5, 3.14]
# - xyz: [path,2.68, 1.425, 0.] 
# # - xyz: [dock,2.68, 1.425, 0.]  
# - xyz: [dock,2.77, 1.425, 0.]  # Best-pot
# - xyz: [dock,2.68, 1.425, 1.57]
# - xyz: [dock,2.68, 1.625, 1.57]
# - xyz: [dock,2.68, 1.355, 3.14]
# - xyz: [dock,2.8, 1.355, 3.14]
# - xyz: [dock,2.72, 1.355, -1.57]
# - xyz: [dock,2.72, 1.525, -1.57]
# - xyz: [dock,2.72, 1.355, 0.0]
# - xyz: [dock,2.835, 1.355, 0.0]
# - xyz: [dock,2.600, 1.355, 0.0]
# - xyz: [path,2.237, 1.64, 1.57]
# # - xyz: [dock,2.237, 1.64, 1.57] 
# - xyz: [dock,2.237, 1.8, 1.57]  # Planter
# - xyz: [dock,2.237, 1.7, 1.57]
# - xyz: [path,1.0, 0.3, 3.14] 
# # - xyz: [dock,1.0, 0.2, 3.14]   
# - xyz: [dock,1.2, 0.2, 3.14]    # Solar-A
# - xyz: [dock,1.4, 0.2, 3.14]
# - xyz: [dock,1.6, 0.2, 3.14]
# - xyz: [dock,1.7, 0.2, 0.]
# - xyz: [dock,2.0, 0.2, 0.]  
# - xyz: [dock,2.7, 0.2, 0.]     # Solar-B

# - xyz: [path,0.86, 0.7, 0.0]
# - xyz: [dock,0.86, 0.7, 0.0] 
# - xyz: [dock,0.75, 0.7, 3.14]
# - xyz: [dock,0.93, 0.7, 3.14]
# - xyz: [path, 0.3, 0.7, 0]
# - xyz: [dock, 0.7, 1.60, 3.14]
# - xyz: [dock, 0.7, 0.7, 0]

#------------------MAP--------------------

# |-------------------------------------|
# |    |   |    | ------- | 13 |   | 17 |
# |_*1_|   |_*7_|   9     |____|   |____|
# |                                |*19 |
# |   *3     5   *11        15     |    |
# |------                          -----|
# |   *4     8               *16   | 18 |
# |____     __   *10     __    |____|
# | *2 |   |    |   12    |    |   |    |
# |    |   | 6  | ------- |  *14   | 20 |    
# |-------------------------------------|

# *means there is an offset to avoid collisions

#----------------POINTS-------------------

# initial place
- xyz: [path, 2.65, 1.00, 0]
- xyz: [path,2.3 , 0.7 , 0.0]  
# - xyz: [dock,2.3 , 0.7 , 0.0]    # Planter-A
- xyz: [dock,2.14 , 0.7 , 0.0]
- xyz: [dock,2.35 , 0.7, 3.14]
- xyz: [dock,2.07, 0.7, 3.14]
- xyz: [path,2.3 , 1.3, 0.0] 
# - xyz: [dock,2.3 , 1.3, 0.0]    # Planter-B
# - xyz: [dock,2.14 , 1.3 , 0.0]
# - xyz: [dock,2.35, 1.3 , 3.14]
# - xyz: [dock,2.07 , 1.3 , 3.14]
# - xyz: [path,1.8 , 1.5, 0,0] 
# # - xyz: [dock,1.8 , 1.5, 0,0]    # Planter-C
# - xyz: [dock,1.64 , 1.5 , 0.0]
# - xyz: [dock,1.85 , 1.5 , 3.14]
# - xyz: [dock,1.57 , 1.5 , 3.14]
# - xyz: [path,0.32, 1.425, 0.] 
# # - xyz: [dock,0.32, 1.425, 0.]  # Best-pot
# - xyz: [dock,0.21, 1.425, 0.]
# - xyz: [dock,0.32, 1.425, -1.57]
# - xyz: [dock,0.32, 1.625, -1.57]
# - xyz: [dock,0.32, 1.355, -3.14]
# - xyz: [dock,0.2, 1.355, -3.14]
# - xyz: [dock,0.28, 1.355, 1.57]
# - xyz: [dock,0.28, 1.525, 1.57]
# - xyz: [dock,0.28, 1.355, 0.0]
# - xyz: [dock,0.165, 1.355, 0.0]
# - xyz: [path,0.75, 1.64, 1.57]
# # - xyz: [dock,0.75, 1.64, 1.57] # Planter
# - xyz: [dock,0.75, 1.8, 1.57]
# - xyz: [dock,0.75, 1.7, 1.57]
# - xyz: [path,1.95, 0.3, 3.14] 
# # - xyz: [dock,1.95, 0.3, 3.14]   # Solar-A
# - xyz: [dock,1.75, 0.3, 3.14]
# - xyz: [dock,1.55, 0.3, 3.14]
# - xyz: [dock,1.35, 0.3, 3.14]
# - xyz: [dock,1.25, 0.3, 0.]
# - xyz: [dock,0.95, 0.3, 0.] 
# - xyz: [dock,0.3, 0.3, 0.]   
# - xyz: [dock,2.7, 0.3, 0.]